version: '3.8'

# Production Docker Compose for Azure Container Instances or Azure Container Apps
services:
  mcp-scheduler-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Database__Provider=mysql
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - DB_PASSWORD=${DB_PASSWORD}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=McpScheduler
      - Jwt__Audience=McpScheduler
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
